### PR TITLE
Add support for min/max label number formatters

### PR DESCRIPTION
**Pull request by cameroncooke**
Adds support for individual number formatters for each label.

### CODE REVIEW

**Comment by cameroncooke** [comment]
This is useful when you need to be able to format each label differently, in our use case we wanted the max value to show a `+` prefix when set to the maximum value. 

```
£0                               £100+
|----------------------------------|
```

With this change we can change the formatter to add the prefix in response to the delegate `rangeSlider: didChangeSelectedMinimumValue:andMaximumValue:` method.

**Comment by TomThorpe** [comment]
Hey, thanks for this!

I'm curious about this one, I'm not opposed to it at all, but I just want to start keeping an eye on what goes into the API as it's got so many options now and I think in the past I just let people add what they needed and now it's getting quite complex.

Could what you want be achieved by extending NSNumberFormatter, and implementing stringForObjectValue so that if the value = maxvalue of the slider, it adds the "+" suffix. I think this would then work for both handles without needing separate formatters? Or am I missing something obvious? 

My intention of having the custom formatter property was to hope that people could customise the logic of what gets displayed in any way they liked, so I'm hoping this is a possible use case for that?

Thanks again for your contribution!

**Comment by cameroncooke** [comment]
Ok that's really neat, didn't even know that method existed. Will give that a go, thanks.

**Comment by TomThorpe** [comment]
Please reopen if you still ended up thinking this would be useful :-)

**Pull request closed without merging**
