### PR TITLE
Issue 61: Feature request: Shadow support for handles

### PR DESCRIPTION
**Pull request by redcapua**
Issue #61 
Feature request: Shadow support for handles

### CODE REVIEW

**Comment by TomThorpe** [comment]
Thanks for this!

Just wanted to check, what’s the purpose of removing the left handle from the superview then adding the right handle back (twice) in the opacity and radius methods?

Thanks!
Tom

**Comment by redcapua** [comment]
That was a typo.
Sorry for that :(

**Comment by TomThorpe** [comment]
No problem at all! :-)

But I just mean the `[self.leftHandle removeFromSuperlayer];` , `[self.layer addSublayer:self.leftHandle];` and `[self.layer addSublayer:self.rightHandle];` lines entirely. I'm just wondering why they need to be there? Or if they can be removed entirely?
 
I dont think it should be needed to remove the handles from the superview and re-add them after the change? I've just tried checking out your branch and removing those lines completely and it still seemed to work fine - so I was just wondering if I had missed a reason for them being there?

Thanks again for your contribution :-)

**Comment by redcapua** [comment]
> I dont think it should be needed to remove the handles from the superview and re-add them after the change?

It is a habit :)
Remove object from view before changing to avoid conflict in the future changes.

In any case it is your repository, and your rules :)

**Comment by TomThorpe** [comment]
Gotcha. Yeah I think it's best to remove those lines if you dont mind, then we can get this merged! 👍

**Comment by redcapua** [comment]
Sure!
Will do and push update

2018-12-05 0:08 GMT+02:00, Tom Thorpe <notifications@github.com>:
> Gotcha. Yeah I think it's best to remove those lines if you dont mind, then
> we can get this merged! 👍

>

> --

> You are receiving this because you authored the thread.

> Reply to this email directly or view it on GitHub:

> https://github.com/TomThorpe/TTRangeSlider/pull/91#issuecomment-444277734


-- 


-----
Kind regards,
Vlad

**Comment by redcapua** [comment]
Lines:
`    [self.leftHandle removeFromSuperlayer];`
have been removed.

**Comment by TomThorpe** [comment]
Thanks, but it was also the `[self.layer addSublayer:self.leftHandle];` and `[self.layer addSublayer:self.rightHandle]` lines too! We don't need those either if we're never removing the layer. I maybe should've just annotated the changes :-)

**Comment by redcapua** [comment]
Removed:
```
    [self.layer addSublayer:self.leftHandle];
    [self.layer addSublayer:self.rightHandle];

```

**Comment by TomThorpe** [comment]
LGTM 👍

**Pull request merged**
